/**
 * Data catalog for generating app detail pages and derivative API docs.
 * Each app entry includes metadata, description, API endpoints used, and screenshots.
 */

export const SEGMENTS = [
  { name: "Consumer", color: "#10b981", icon: "\u2605" },
  { name: "Dealer", color: "#f59e0b", icon: "\u2699" },
  { name: "Appraiser", color: "#3b82f6", icon: "\u2696" },
  { name: "Dealership Group", color: "#f97316", icon: "\u25A0" },
  { name: "Lender", color: "#06b6d4", icon: "\u2666" },
  { name: "Analyst", color: "#8b5cf6", icon: "\u25B2" },
  { name: "Insurer", color: "#ec4899", icon: "\u2665" },
  { name: "Manufacturer", color: "#ef4444", icon: "\u2605" },
  { name: "Auction House", color: "#84cc16", icon: "\u25B6" },
  { name: "Wholesaler", color: "#78716c", icon: "\u2666" },
  { name: "Cross-Segment", color: "#a78bfa", icon: "\u2296" },
  { name: "Consumer (UK)", color: "#10b981", icon: "\u2605" },
  { name: "Dealer (UK)", color: "#f59e0b", icon: "\u2699" },
  { name: "Auto Media", color: "#d946ef", icon: "\u270E" },
  { name: "Fleet Manager", color: "#059669", icon: "\u2699" },
  { name: "Rental/Subscription", color: "#0ea5e9", icon: "\u2666" },
  { name: "Lender Sales", color: "#14b8a6", icon: "\u2197" },
  { name: "Chat Demos", color: "#6366f1", icon: "\uD83D\uDCAC" },
];

export const MC_API_ENDPOINTS = {
  decode: { path: "GET /v2/decode/car/neovin/{vin}/specs", name: "VIN Decode", docs: "https://apidocs.marketcheck.com/#decode-vin" },
  predict: { path: "GET /v2/predict/car/us/marketcheck_price/comparables", name: "Price Prediction", docs: "https://apidocs.marketcheck.com/#price-prediction" },
  searchActive: { path: "GET /v2/search/car/active", name: "Search Active Listings", docs: "https://apidocs.marketcheck.com/#search-active" },
  searchRecent: { path: "GET /v2/search/car/recents", name: "Search Recent/Sold", docs: "https://apidocs.marketcheck.com/#search-recent" },
  history: { path: "GET /v2/history/car/{vin}", name: "Car History", docs: "https://apidocs.marketcheck.com/#car-history" },
  soldSummary: { path: "GET /api/v1/sold-vehicles/summary", name: "Sold Vehicle Summary", docs: "https://apidocs.marketcheck.com/#sold-summary" },
  incentives: { path: "GET /v2/incentives/by-zip", name: "OEM Incentives", docs: "https://apidocs.marketcheck.com/#incentives" },
  ukActive: { path: "GET /v2/search/car/uk/active", name: "UK Active Listings", docs: "https://apidocs.marketcheck.com/#uk-search" },
  ukRecent: { path: "GET /v2/search/car/uk/recents", name: "UK Recent Listings", docs: "https://apidocs.marketcheck.com/#uk-recent" },
};

export const APPS = [
  // ── Consumer ──
  {
    id: "vin-market-report", name: "VIN Market Report", tagline: "VIN-based market report \u2014 embeddable widget like CarStory.ai",
    segment: "Consumer", tool: "generate-vin-market-report",
    description: "A comprehensive market intelligence report for any vehicle by VIN. Includes deal score, price prediction (retail & wholesale), market position percentile, active and sold comparables, listing history timeline, depreciation curve, and available OEM incentives. Designed as an embeddable widget for dealer websites, marketplace listings, or financing portals.",
    apiEndpoints: ["decode", "predict", "searchActive", "searchRecent", "history", "incentives"],
    inputParams: [
      { name: "vin", type: "string", required: true, desc: "17-character VIN" },
      { name: "askingPrice", type: "number", required: false, desc: "Dealer asking price for deal score" },
      { name: "miles", type: "number", required: false, desc: "Current odometer reading" },
      { name: "zip", type: "string", required: false, desc: "ZIP code for regional pricing" },
    ],
  },
  {
    id: "car-search-compare", name: "Car Search & Compare", tagline: "Find and compare cars side by side",
    segment: "Consumer", tool: "search-cars,compare-cars",
    description: "Visual car shopping experience with powerful filters (make, model, body type, price, year, mileage, fuel type, location) and side-by-side comparison of 2-3 vehicles. Shows full specs, predicted prices, and key differences. Photo cards with dealer info and days-on-market indicators.",
    apiEndpoints: ["searchActive", "decode", "predict"],
    inputParams: [
      { name: "makes", type: "string", required: false, desc: "Comma-separated makes" },
      { name: "bodyTypes", type: "string", required: false, desc: "Body types, e.g. 'SUV,Sedan'" },
      { name: "priceRange", type: "string", required: false, desc: "Price range, e.g. '15000-45000'" },
      { name: "zip", type: "string", required: false, desc: "ZIP code for location-based search" },
      { name: "vins", type: "string[]", required: false, desc: "Array of 2-3 VINs to compare" },
    ],
  },
  {
    id: "car-search-app", name: "Car Search", tagline: "Full search with SERP, vehicle details, and NLP search",
    segment: "Consumer", tool: "search-cars",
    description: "Full-featured car search with three views: SERP (search results page with filters and photo cards), vehicle details (full specs, photos, pricing, dealer info), and natural language search (type queries like 'Red Toyota Camry under $25K near Denver'). Supports pagination, sorting, and faceted filtering.",
    apiEndpoints: ["searchActive", "decode", "predict"],
    inputParams: [
      { name: "makes", type: "string", required: false, desc: "Comma-separated makes" },
      { name: "zip", type: "string", required: false, desc: "ZIP code" },
      { name: "query", type: "string", required: false, desc: "Natural language search query" },
    ],
  },
  {
    id: "deal-evaluator", name: "Deal Evaluator", tagline: "Should I buy this car? Get a Buy/Negotiate/Pass verdict",
    segment: "Consumer", tool: "evaluate-deal",
    description: "Enter a VIN and asking price to get a data-driven Buy/Negotiate/Pass verdict. Shows gauge visualization of deal quality, predicted fair market price, percentile ranking against comparable vehicles, price history timeline, negotiation leverage points, and cheaper alternatives nearby.",
    apiEndpoints: ["decode", "predict", "searchActive", "history"],
    inputParams: [
      { name: "vin", type: "string", required: true, desc: "17-character VIN" },
      { name: "askingPrice", type: "number", required: false, desc: "Dealer asking price" },
      { name: "miles", type: "number", required: false, desc: "Current mileage" },
      { name: "zip", type: "string", required: false, desc: "Buyer's ZIP code" },
    ],
  },
  {
    id: "incentive-adjusted-deal-eval", name: "Incentive-Adjusted Deal Evaluator", tagline: "True out-of-pocket cost after rebates and APR savings",
    segment: "Consumer", tool: "evaluate-incentive-deal",
    description: "Evaluates a deal with OEM incentives factored in. Decodes the VIN, predicts market price, fetches all available manufacturer incentives (cash back, APR specials, lease deals), and calculates the true out-of-pocket cost. Shows comparable active listings for price benchmarking.",
    apiEndpoints: ["decode", "predict", "incentives", "searchActive"],
    inputParams: [
      { name: "vin", type: "string", required: true, desc: "17-character VIN" },
      { name: "miles", type: "number", required: false, desc: "Current mileage" },
      { name: "zip", type: "string", required: true, desc: "ZIP code for incentives" },
    ],
  },
  {
    id: "trade-in-estimator", name: "Trade-In Estimator", tagline: "What's your car worth? 3-tier instant valuation",
    segment: "Consumer", tool: "estimate-trade-in",
    description: "Three-tier instant valuation: retail (private party), trade-in (dealer offer), and instant cash (quick sale). Uses VIN decode for exact specs, ML price prediction for retail and wholesale values, and recent sold comparables for market validation. Condition-adjusted with tips to maximize value.",
    apiEndpoints: ["decode", "predict", "searchRecent"],
    inputParams: [
      { name: "vin", type: "string", required: true, desc: "17-character VIN" },
      { name: "miles", type: "number", required: true, desc: "Current mileage" },
      { name: "zip", type: "string", required: true, desc: "ZIP code" },
      { name: "condition", type: "string", required: true, desc: "excellent, good, fair, or poor" },
    ],
  },
  {
    id: "used-car-market-index", name: "Used Car Market Index", tagline: "Track prices like Wall Street tracks stocks",
    segment: "Consumer", tool: "get-market-index",
    description: "Stock-ticker-style dashboard that tracks used car market trends. Shows top 25 brands by volume and average sale price, body type segment analysis, demand-to-supply ratios, and price trend indicators. Filterable by state for regional insights.",
    apiEndpoints: ["soldSummary"],
    inputParams: [
      { name: "state", type: "string", required: false, desc: "US state abbreviation" },
    ],
  },
  {
    id: "oem-incentives-explorer", name: "OEM Incentives Explorer", tagline: "Cash back, APR, and lease deals by ZIP",
    segment: "Consumer", tool: "oem-incentives-explorer",
    description: "Search and compare manufacturer incentives by ZIP code. Shows cash back rebates, APR financing specials, lease deals, and loyalty bonuses. Compare incentives across multiple brands side-by-side to find the best overall deal.",
    apiEndpoints: ["incentives"],
    inputParams: [
      { name: "make", type: "string", required: true, desc: "Manufacturer name" },
      { name: "model", type: "string", required: false, desc: "Specific model" },
      { name: "zip", type: "string", required: true, desc: "ZIP code" },
      { name: "compareMakes", type: "string[]", required: false, desc: "Brands to compare" },
    ],
  },
  {
    id: "incentive-deal-finder", name: "Incentive Deal Finder", tagline: "Search ALL OEM incentives by budget, not by brand",
    segment: "Consumer", tool: "find-incentive-deals",
    description: "Scans incentives from 10+ major manufacturers simultaneously for a given ZIP code. Aggregates and ranks all available deals \u2014 cash back, financing specials, lease offers \u2014 so shoppers can find the best incentives regardless of brand loyalty.",
    apiEndpoints: ["incentives"],
    inputParams: [
      { name: "makes", type: "string", required: false, desc: "Comma-separated makes (defaults to top 10)" },
      { name: "zip", type: "string", required: true, desc: "ZIP code" },
    ],
  },
  // ── Dealer ──
  {
    id: "lot-pricing-dashboard", name: "Lot Pricing Dashboard", tagline: "See your entire lot priced against the market",
    segment: "Dealer", tool: "scan-lot-pricing",
    description: "Full dealer inventory view with market price gaps, aging heatmap (0-30, 30-60, 60-90, 90+ days), floor plan burn rate, and stocking hot list from demand data. Each vehicle shows listed price vs market price, gap percentage, days on market, and comp count. KPIs include total units, avg DOM, aged units, and overpriced percentage.",
    apiEndpoints: ["searchActive", "predict", "soldSummary"],
    inputParams: [
      { name: "dealerId", type: "string", required: true, desc: "MarketCheck Dealer ID" },
      { name: "zip", type: "string", required: true, desc: "Dealer ZIP code" },
      { name: "state", type: "string", required: true, desc: "State for demand data" },
    ],
  },
  {
    id: "stocking-intelligence", name: "Stocking Intelligence", tagline: "Know what to buy at auction",
    segment: "Dealer", tool: "stocking-intelligence",
    description: "Demand heatmap showing what's selling in your market by make/model and body type. Includes buy/avoid recommendations, demand-to-supply ratios, average days on market, and average sale prices. Filter by state for regional stocking guidance.",
    apiEndpoints: ["soldSummary"],
    inputParams: [
      { name: "state", type: "string", required: true, desc: "US state abbreviation" },
    ],
  },
  {
    id: "pricing-transparency-report", name: "Pricing Transparency Report", tagline: "Shareable market report dealers give buyers",
    segment: "Dealer", tool: "generate-pricing-report",
    description: "Generate a professional, shareable pricing report for a specific vehicle. Shows VIN-decoded specs, ML-predicted fair market price, active comparables in the area, and recent sold vehicle data. Designed to be printed or emailed to buyers as evidence of fair pricing.",
    apiEndpoints: ["decode", "predict", "searchActive", "searchRecent"],
    inputParams: [
      { name: "vin", type: "string", required: true, desc: "17-character VIN" },
      { name: "miles", type: "number", required: false, desc: "Current mileage" },
      { name: "zip", type: "string", required: false, desc: "ZIP code" },
    ],
  },
  {
    id: "dealer-inventory-fit-scorer", name: "Dealer Inventory Fit Scorer", tagline: "Which cars match your sales DNA?",
    segment: "Dealer", tool: "score-dealer-fit",
    description: "Score a batch of VINs against a dealer's sales profile. Each vehicle gets decoded and priced against market to determine fit. Helps dealers evaluate auction run lists and wholesale opportunities against their typical inventory mix.",
    apiEndpoints: ["decode", "predict"],
    inputParams: [
      { name: "dealer_id", type: "string", required: true, desc: "Dealer ID" },
      { name: "vins", type: "string", required: true, desc: "Comma-separated VINs" },
      { name: "zip", type: "string", required: true, desc: "Dealer ZIP" },
    ],
  },
  {
    id: "dealer-conquest-analyzer", name: "Dealer Conquest Analyzer", tagline: "Find competitors' best-sellers you should stock",
    segment: "Dealer", tool: "analyze-dealer-conquest",
    description: "Compares your inventory against the broader market within your radius. Identifies gaps \u2014 makes, models, and body types that are selling well in your market but missing from your lot. Uses sold demand data to rank conquest opportunities.",
    apiEndpoints: ["searchActive", "soldSummary"],
    inputParams: [
      { name: "dealer_id", type: "string", required: true, desc: "Your Dealer ID" },
      { name: "zip", type: "string", required: true, desc: "Market center ZIP" },
      { name: "radius", type: "number", required: false, desc: "Market radius (default 50 mi)" },
      { name: "state", type: "string", required: true, desc: "State for demand data" },
    ],
  },
  // ── Appraiser ──
  {
    id: "appraiser-workbench", name: "Appraiser Workbench", tagline: "Complete vehicle valuation studio",
    segment: "Appraiser", tool: "appraiser-workbench",
    description: "The most comprehensive valuation tool. Provides retail and wholesale price predictions, both active and sold comparables (25 each), full listing history, and VIN-decoded specs. Designed for professional appraisers who need defensible, data-backed valuations for trade-ins, insurance claims, estate valuations, and fleet revaluation.",
    apiEndpoints: ["decode", "predict", "searchActive", "searchRecent", "history"],
    inputParams: [
      { name: "vin", type: "string", required: true, desc: "17-character VIN" },
      { name: "miles", type: "number", required: false, desc: "Current mileage" },
      { name: "zip", type: "string", required: false, desc: "ZIP code" },
    ],
  },
  {
    id: "comparables-explorer", name: "Comparables Explorer", tagline: "Price distribution and market positioning",
    segment: "Appraiser", tool: "comparables-explorer",
    description: "Flexible comparable search by VIN or make/model/year. Shows active listings (up to 50) and sold listings (up to 25) with price distribution, stats, and optional price prediction. Adjustable search radius for broad or narrow market analysis.",
    apiEndpoints: ["decode", "predict", "searchActive", "searchRecent"],
    inputParams: [
      { name: "vin", type: "string", required: false, desc: "VIN (optional \u2014 or use make/model)" },
      { name: "make", type: "string", required: false, desc: "Vehicle make" },
      { name: "model", type: "string", required: false, desc: "Vehicle model" },
      { name: "year", type: "string", required: false, desc: "Year or range" },
      { name: "zip", type: "string", required: false, desc: "ZIP code" },
      { name: "radius", type: "number", required: false, desc: "Search radius (default 100 mi)" },
    ],
  },
  {
    id: "depreciation-analyzer", name: "Depreciation Analyzer", tagline: "Track how vehicles lose value over time",
    segment: "Appraiser", tool: "depreciation-analyzer",
    description: "Visualizes depreciation curves by tracking price trends for a make/model over multiple model years. Shows MSRP-to-market-price ratios, annual depreciation rates, and value retention rankings across body types and segments.",
    apiEndpoints: ["soldSummary", "searchActive"],
    inputParams: [
      { name: "make", type: "string", required: true, desc: "Vehicle make" },
      { name: "model", type: "string", required: false, desc: "Vehicle model" },
    ],
  },
  {
    id: "market-trends-dashboard", name: "Market Trends Dashboard", tagline: "The pulse of the automotive market",
    segment: "Appraiser", tool: "market-trends-dashboard",
    description: "Macro-level market intelligence dashboard showing price trends, inventory levels, days-on-market averages, and demand signals across segments. Uses sold summary data for trend analysis and active inventory for supply-side metrics.",
    apiEndpoints: ["soldSummary", "searchActive"],
    inputParams: [
      { name: "state", type: "string", required: false, desc: "State filter" },
    ],
  },
  // ── Dealership Group ──
  {
    id: "group-operations-center", name: "Group Operations Center", tagline: "Every store, one screen",
    segment: "Dealership Group", tool: "group-operations-center",
    description: "Unified dashboard for multi-location dealer groups. Shows per-location KPIs (inventory count, avg DOM, aged units, pricing health), cross-location comparison, and group-level rollup metrics. Identify underperforming locations at a glance.",
    apiEndpoints: ["searchActive", "soldSummary"],
    inputParams: [
      { name: "dealerIds", type: "string", required: true, desc: "Comma-separated dealer IDs" },
    ],
  },
  {
    id: "inventory-balancer", name: "Inventory Balancer", tagline: "Move the right cars to the right stores",
    segment: "Dealership Group", tool: "inventory-balancer",
    description: "Identifies transfer opportunities across locations. Finds vehicles that are slow movers at one store but in high demand at another, recommending inter-location transfers for faster turns and better margins.",
    apiEndpoints: ["searchActive", "soldSummary"],
    inputParams: [
      { name: "dealerIds", type: "string", required: true, desc: "Comma-separated dealer IDs" },
      { name: "state", type: "string", required: true, desc: "State for demand data" },
    ],
  },
  {
    id: "location-benchmarking", name: "Location Benchmarking", tagline: "Rank and compare your locations",
    segment: "Dealership Group", tool: "location-benchmarking",
    description: "Benchmarks each location against the others in your group on key metrics: average DOM, aged inventory %, pricing accuracy, inventory turnover, and demand alignment. Identifies best practices from top-performing stores.",
    apiEndpoints: ["searchActive", "soldSummary"],
    inputParams: [
      { name: "dealerIds", type: "string", required: true, desc: "Comma-separated dealer IDs" },
    ],
  },
  // ── Lender ──
  {
    id: "underwriting-decision-support", name: "Underwriting Decision Support", tagline: "Single-loan collateral valuation with LTV forecast",
    segment: "Lender", tool: "evaluate-loan-application",
    description: "Comprehensive collateral assessment for auto loan underwriting. Provides retail and wholesale valuations, listing history for depreciation trajectory, and recent sold comps. Calculates LTV at origination and forecasts collateral erosion over the loan term.",
    apiEndpoints: ["decode", "predict", "history", "searchRecent"],
    inputParams: [
      { name: "vin", type: "string", required: true, desc: "17-character VIN" },
      { name: "miles", type: "number", required: false, desc: "Current mileage" },
      { name: "zip", type: "string", required: false, desc: "Borrower ZIP" },
    ],
  },
  {
    id: "portfolio-risk-monitor", name: "Portfolio Risk Monitor", tagline: "Track collateral health across your loan book",
    segment: "Lender", tool: "portfolio-risk-monitor",
    description: "Portfolio-level collateral monitoring. Tracks value changes across your loan book, flags vehicles with rapid depreciation, identifies underwater loans, and segments risk by vehicle type, age, and region.",
    apiEndpoints: ["decode", "predict", "soldSummary"],
    inputParams: [
      { name: "vins", type: "string", required: true, desc: "Comma-separated portfolio VINs" },
      { name: "zip", type: "string", required: true, desc: "Primary market ZIP" },
    ],
  },
  {
    id: "lender-portfolio-stress-test", name: "Lender Portfolio Stress Test", tagline: "What-if depreciation scenarios on your loan book",
    segment: "Lender", tool: "stress-test-portfolio",
    description: "Stress test a portfolio of VINs against depreciation scenarios. Decodes each VIN and predicts current market value, then models impact of 10%, 20%, and 30% value drops on portfolio LTV and loss exposure.",
    apiEndpoints: ["decode", "predict"],
    inputParams: [
      { name: "vins", type: "string", required: true, desc: "Comma-separated VINs" },
      { name: "zip", type: "string", required: true, desc: "ZIP code" },
    ],
  },
  {
    id: "ev-collateral-risk", name: "EV Collateral Risk Monitor", tagline: "EV vs ICE depreciation risk tracking",
    segment: "Lender", tool: "ev-collateral-risk",
    description: "Tracks depreciation divergence between EV and ICE vehicles in your portfolio. Monitors EV-specific risks: battery degradation proxy (age + mileage), rapid model year devaluation, and regional EV demand variations.",
    apiEndpoints: ["decode", "predict", "soldSummary"],
    inputParams: [
      { name: "vins", type: "string", required: true, desc: "Portfolio VINs" },
      { name: "zip", type: "string", required: true, desc: "Market ZIP" },
    ],
  },
  // ── Analyst ──
  {
    id: "earnings-signal-dashboard", name: "Earnings Signal Dashboard", tagline: "Pre-earnings channel check for auto tickers",
    segment: "Analyst", tool: "earnings-signal-dashboard",
    description: "Leading indicators for publicly traded automotive companies. Tracks inventory levels, pricing power, demand trends, and days-on-market as forward signals for OEM and dealer group earnings. Cross-references sold data for volume momentum.",
    apiEndpoints: ["searchActive", "soldSummary"],
    inputParams: [
      { name: "tickers", type: "string", required: true, desc: "Auto industry ticker symbols" },
    ],
  },
  {
    id: "watchlist-monitor", name: "Watchlist Monitor", tagline: "Morning signal scan across your portfolio",
    segment: "Analyst", tool: "watchlist-monitor",
    description: "Daily scan of market signals for your tracked automotive tickers. Highlights significant inventory changes, pricing shifts, demand anomalies, and competitive positioning changes that may impact stock valuations.",
    apiEndpoints: ["searchActive", "soldSummary"],
    inputParams: [
      { name: "tickers", type: "string", required: true, desc: "Watchlist tickers" },
    ],
  },
  {
    id: "dealer-group-scorecard", name: "Dealer Group Scorecard", tagline: "Benchmark public dealer groups",
    segment: "Analyst", tool: "dealer-group-scorecard",
    description: "Operational benchmarking of publicly traded dealer groups (AutoNation, Lithia, Penske, etc.). Compares inventory efficiency, pricing accuracy, market coverage, and segment mix across the largest dealer networks.",
    apiEndpoints: ["searchActive", "soldSummary"],
    inputParams: [
      { name: "groups", type: "string", required: true, desc: "Dealer group names" },
    ],
  },
  // ── Insurer ──
  {
    id: "claims-valuation-workbench", name: "Claims Valuation Workbench", tagline: "Total-loss determination with market evidence",
    segment: "Insurer", tool: "claims-valuation",
    description: "Insurance claims valuation tool for total-loss determination. Provides fair market value using ML prediction, recent sold comparables within the claim area, regional pricing summary by state, and replacement vehicle options. All evidence needed for a defensible settlement.",
    apiEndpoints: ["decode", "predict", "searchRecent", "soldSummary", "searchActive"],
    inputParams: [
      { name: "vin", type: "string", required: true, desc: "Claimed vehicle VIN" },
      { name: "miles", type: "number", required: false, desc: "Mileage at time of loss" },
      { name: "zip", type: "string", required: true, desc: "Claim location ZIP" },
    ],
  },
  {
    id: "insurance-premium-benchmarker", name: "Insurance Premium Benchmarker", tagline: "Segment-level replacement cost and risk analysis",
    segment: "Insurer", tool: "benchmark-insurance-premiums",
    description: "Market-level analysis of replacement costs and risk factors by body type, fuel type, and state. Helps underwriters set premiums based on actual market data: average replacement costs, volume patterns, and regional price variations.",
    apiEndpoints: ["soldSummary"],
    inputParams: [],
  },
  // ── Manufacturer ──
  {
    id: "brand-command-center", name: "Brand Command Center", tagline: "Your brands vs the competition",
    segment: "Manufacturer", tool: "brand-command-center",
    description: "OEM competitive intelligence dashboard. Tracks your brand's market share, pricing power, inventory levels, and demand trends vs competitors. Segment-level analysis (SUV, sedan, truck, EV) with regional breakdowns.",
    apiEndpoints: ["searchActive", "soldSummary"],
    inputParams: [
      { name: "brand", type: "string", required: true, desc: "Your OEM brand" },
      { name: "competitors", type: "string", required: false, desc: "Competitor brands" },
    ],
  },
  {
    id: "regional-demand-allocator", name: "Regional Demand Allocator", tagline: "Allocate inventory where demand is hottest",
    segment: "Manufacturer", tool: "regional-demand-allocator",
    description: "Demand heatmap by state and region. Shows where your models are selling fastest, where inventory is building up, and optimal allocation recommendations based on demand-to-supply ratios across markets.",
    apiEndpoints: ["soldSummary", "searchActive"],
    inputParams: [
      { name: "brand", type: "string", required: true, desc: "Your brand" },
    ],
  },
  // ── Auction House ──
  {
    id: "auction-lane-planner", name: "Auction Lane Planner", tagline: "Plan lanes, price consignments, target buyers",
    segment: "Auction House", tool: "auction-lane-planner",
    description: "Auction planning tool for lane organization and consignment pricing. Groups vehicles by segment, estimates expected hammer prices using retail/wholesale predictions, and identifies likely buyer profiles based on local dealer demand patterns.",
    apiEndpoints: ["decode", "predict", "soldSummary"],
    inputParams: [
      { name: "vins", type: "string", required: true, desc: "Consignment VINs" },
      { name: "zip", type: "string", required: true, desc: "Auction location ZIP" },
    ],
  },
  {
    id: "auction-arbitrage-finder", name: "Auction Arbitrage Finder", tagline: "Wholesale vs retail spread \u2014 find profit opportunities",
    segment: "Auction House", tool: "find-auction-arbitrage",
    description: "Identifies vehicles with the largest wholesale-to-retail spread. For each VIN, predicts both franchise (retail) and independent (wholesale) values to calculate potential arbitrage profit. Helps wholesalers and dealers find the most profitable auction purchases.",
    apiEndpoints: ["decode", "predict"],
    inputParams: [
      { name: "vins", type: "string", required: true, desc: "Comma-separated VINs" },
      { name: "zip", type: "string", required: true, desc: "Market ZIP" },
    ],
  },
  // ── Wholesaler ──
  {
    id: "wholesale-vehicle-router", name: "Wholesale Vehicle Router", tagline: "Paste VINs, get dealer-match rankings",
    segment: "Wholesaler", tool: "route-wholesale-vehicles",
    description: "Batch VIN evaluation for wholesale operations. Decodes each VIN and predicts retail market value to determine optimal routing. Helps wholesalers decide which vehicles to retail, wholesale, or send to specific markets based on regional demand.",
    apiEndpoints: ["decode", "predict"],
    inputParams: [
      { name: "vins", type: "string", required: true, desc: "Comma-separated VINs" },
      { name: "zip", type: "string", required: true, desc: "Primary market ZIP" },
    ],
  },
  // ── Cross-Segment ──
  {
    id: "ev-market-monitor", name: "EV Market Monitor", tagline: "The EV transition in one dashboard",
    segment: "Cross-Segment", tool: "ev-market-monitor",
    description: "Tracks the EV vs ICE transition with real-time market data. Shows EV inventory levels, pricing trends, depreciation rates, adoption curves, and demand signals. Compares EV and ICE metrics across segments and regions.",
    apiEndpoints: ["searchActive", "soldSummary"],
    inputParams: [
      { name: "state", type: "string", required: false, desc: "State filter" },
    ],
  },
  {
    id: "vin-history-detective", name: "VIN History Detective", tagline: "Full listing timeline \u2014 dealer hops, price changes, red flags",
    segment: "Cross-Segment", tool: "trace-vin-history",
    description: "Complete listing timeline for any VIN. Shows every price change, dealer transfer, and listing duration. Flags suspicious patterns (rapid relisting, large price drops, short hold times). Includes current market value prediction for context.",
    apiEndpoints: ["decode", "history", "predict"],
    inputParams: [
      { name: "vin", type: "string", required: true, desc: "17-character VIN" },
      { name: "miles", type: "number", required: false, desc: "Current mileage" },
      { name: "zip", type: "string", required: false, desc: "ZIP code" },
    ],
  },
  {
    id: "market-anomaly-detector", name: "Market Anomaly Detector", tagline: "Find underpriced vehicles and pricing outliers",
    segment: "Cross-Segment", tool: "detect-market-anomalies",
    description: "Statistical outlier detection for car pricing. Searches active inventory for a make/model and flags vehicles priced significantly below or above market (configurable sensitivity in standard deviations). Verifies outliers against ML price predictions to confirm genuine deals vs data errors.",
    apiEndpoints: ["searchActive", "predict"],
    inputParams: [
      { name: "make", type: "string", required: true, desc: "Vehicle make" },
      { name: "model", type: "string", required: true, desc: "Vehicle model" },
      { name: "year", type: "string", required: false, desc: "Year or range" },
      { name: "state", type: "string", required: false, desc: "State filter" },
      { name: "sensitivity", type: "number", required: false, desc: "Std dev threshold (1-3, default 2)" },
    ],
  },
  {
    id: "uk-market-trends", name: "UK Market Trends", tagline: "Macro UK automotive market intelligence",
    segment: "Cross-Segment", tool: "get-uk-market-trends",
    description: "UK automotive market statistics. Shows active and recent inventory levels, average prices in GBP, mileage distributions, and market trends for the UK car market. Filterable by make.",
    apiEndpoints: ["ukActive", "ukRecent"],
    inputParams: [
      { name: "make", type: "string", required: false, desc: "Filter by make" },
    ],
  },
  // ── UK ──
  {
    id: "uk-market-explorer", name: "UK Market Explorer", tagline: "Search and compare UK car listings in GBP",
    segment: "Consumer (UK)", tool: "search-uk-cars",
    description: "Search the UK used car market with filters for make, model, year, price (GBP), mileage, and postal code. Shows active listings with dealer info and recent market comparisons.",
    apiEndpoints: ["ukActive", "ukRecent"],
    inputParams: [
      { name: "make", type: "string", required: false, desc: "Vehicle make" },
      { name: "model", type: "string", required: false, desc: "Vehicle model" },
      { name: "postal_code", type: "string", required: false, desc: "UK postal code" },
      { name: "radius", type: "number", required: false, desc: "Search radius" },
    ],
  },
  {
    id: "uk-dealer-pricing", name: "UK Dealer Pricing", tagline: "UK lot inventory priced against the market",
    segment: "Dealer (UK)", tool: "scan-uk-lot-pricing",
    description: "UK dealer lot pricing dashboard. Shows dealer inventory with market comparison, price gaps, and recent sold data for benchmarking. Similar to the US Lot Pricing Dashboard but for the UK market.",
    apiEndpoints: ["ukActive", "ukRecent"],
    inputParams: [
      { name: "dealer_id", type: "string", required: true, desc: "UK dealer ID" },
      { name: "make", type: "string", required: false, desc: "Make filter for recents" },
    ],
  },
  // ── Auto Media ──
  {
    id: "auto-journalist-briefing", name: "Auto Journalist Briefing", tagline: "One-page market briefing with quotable data points",
    segment: "Auto Media", tool: "generate-market-briefing",
    description: "Executive market summary with quotable data points for automotive journalists. Rankings by make (volume & price), body type analysis, and regional price leaders. Pre-formatted for easy citation in articles and reports.",
    apiEndpoints: ["soldSummary"],
    inputParams: [],
  },
  // ── Fleet/Rental ──
  {
    id: "fleet-lifecycle-manager", name: "Fleet Lifecycle Manager", tagline: "Fleet values, depreciation, and replacement planning",
    segment: "Fleet Manager", tool: "manage-fleet-lifecycle",
    description: "Fleet management tool for tracking vehicle values, depreciation trajectories, and optimal replacement timing. Batch-processes fleet VINs for current market values and suggests replacement vehicles from active inventory.",
    apiEndpoints: ["decode", "predict", "searchActive"],
    inputParams: [
      { name: "vins", type: "string", required: true, desc: "Comma-separated fleet VINs" },
      { name: "zip", type: "string", required: true, desc: "Primary fleet location ZIP" },
    ],
  },
  {
    id: "rental-fleet-valuator", name: "Rental Fleet Valuator", tagline: "Mileage-adjusted fleet valuation with rotation timing",
    segment: "Rental/Subscription", tool: "value-rental-fleet",
    description: "Rental fleet valuation with mileage-adjusted pricing. Evaluates each vehicle in the fleet for current market value, factoring in high-mileage depreciation typical of rental use. Identifies vehicles approaching optimal rotation point.",
    apiEndpoints: ["decode", "predict"],
    inputParams: [
      { name: "vins", type: "string", required: true, desc: "Fleet VINs" },
      { name: "zip", type: "string", required: true, desc: "Fleet location ZIP" },
    ],
  },
  {
    id: "territory-pipeline", name: "Territory Pipeline", tagline: "Find dealers who need floor plan",
    segment: "Lender Sales", tool: "territory-pipeline",
    description: "Sales prospecting tool for floor plan lenders. Analyzes dealer inventory in a territory to identify dealers with high inventory turnover, growing inventory, or signs of needing additional floor plan financing.",
    apiEndpoints: ["searchActive", "soldSummary"],
    inputParams: [
      { name: "state", type: "string", required: true, desc: "Territory state" },
      { name: "zip", type: "string", required: false, desc: "Territory center ZIP" },
    ],
  },
  {
    id: "floor-plan-opportunity-scanner", name: "Floor Plan Opportunity Scanner", tagline: "Find dealers with aging inventory who need floor plan financing",
    segment: "Lender Sales", tool: "scan-floor-plan-opportunities",
    description: "Scans a territory for dealers with high days-on-market inventory — a signal they may need floor plan financing. Calculates estimated floor plan burn per dealer ($35/day/unit), ranks dealers by opportunity size, and flags those with 90+ DOM inventory exceeding 30% of their lot.",
    apiEndpoints: ["searchActive", "soldSummary"],
    inputParams: [
      { name: "zip", type: "string", required: true, desc: "Territory center ZIP" },
      { name: "radius", type: "number", required: false, desc: "Search radius in miles (default: 50)" },
      { name: "min_dom", type: "number", required: false, desc: "Minimum DOM threshold for aged inventory (default: 60)" },
    ],
  },
  {
    id: "dealer-intelligence-brief", name: "Dealer Intelligence Brief", tagline: "Dealer profile data for pitch prep",
    segment: "Lender Sales", tool: "dealer-intelligence-brief",
    description: "One-page dealer intelligence brief for sales call prep. Pulls a dealer's active inventory to analyze size, brand mix, body type mix, pricing patterns, aging health, and estimated floor plan exposure. Everything a lender sales rep needs before walking in the door.",
    apiEndpoints: ["searchActive", "soldSummary"],
    inputParams: [
      { name: "dealer_id", type: "string", required: true, desc: "Target dealer's MarketCheck ID" },
      { name: "zip", type: "string", required: false, desc: "Dealer ZIP for market context (competitor pricing)" },
      { name: "state", type: "string", required: false, desc: "2-letter state code for demand comparison" },
    ],
  },
  {
    id: "subprime-opportunity-finder", name: "Subprime Opportunity Finder", tagline: "Identify subprime-heavy dealers for lending products",
    segment: "Lender Sales", tool: "subprime-opportunity-finder",
    description: "Identifies dealers likely serving subprime buyers by analyzing inventory patterns: high percentage of older vehicles (5+ years), lower price points, independent dealer type, and high DOM. These signals indicate dealers who may need subprime lending products or BHPH financing partnerships.",
    apiEndpoints: ["searchActive", "soldSummary"],
    inputParams: [
      { name: "zip", type: "string", required: true, desc: "Target market ZIP code" },
      { name: "radius", type: "number", required: false, desc: "Search radius in miles (default: 50)" },
      { name: "state", type: "string", required: false, desc: "2-letter state code for sold demand context" },
    ],
  },
  // ── Chat Demos ──
  {
    id: "chat-vercel-ai", name: "AI Car Advisor (Vercel AI SDK)", tagline: "Conversational car shopping with Claude streaming",
    segment: "Chat Demos", tool: "chat",
    description: "Reference chat implementation using the Vercel AI SDK pattern. Features streaming responses, tool call visualization with status chips, and collapsible tool result details. Supports Anthropic Claude, OpenAI GPT-4o, and Google Gemini as LLM providers.",
    apiEndpoints: ["searchActive", "decode", "predict", "history", "incentives", "soldSummary"],
    inputParams: [],
  },
  {
    id: "chat-copilotkit", name: "Dashboard Copilot (CopilotKit)", tagline: "AI copilot overlay on existing dashboards",
    segment: "Chat Demos", tool: "chat",
    description: "Demonstrates the CopilotKit pattern \u2014 an AI copilot overlay that sits alongside existing dashboard content. The chat interface is a sidebar that can query automotive market data while the main dashboard displays summary metrics.",
    apiEndpoints: ["searchActive", "decode", "predict", "history", "incentives", "soldSummary"],
    inputParams: [],
  },
  {
    id: "chat-assistant-ui", name: "MarketCheck Chat (assistant-ui)", tagline: "Custom-branded chat with rich tool result cards",
    segment: "Chat Demos", tool: "chat",
    description: "Showcases the assistant-ui pattern with custom-branded noir theme and rich tool result cards. Search results render as visual car listing grids, VIN decodes as spec sheets, and price predictions as highlighted value cards. The most visually polished chat demo.",
    apiEndpoints: ["searchActive", "decode", "predict", "history", "incentives", "soldSummary"],
    inputParams: [],
  },
  {
    id: "chat-sdk-bot", name: "Multi-Platform Bot (Chat SDK)", tagline: "One bot for Slack, Discord, Telegram, and Teams",
    segment: "Chat Demos", tool: "chat",
    description: "Demonstrates the Chat SDK (chat-sdk.dev) pattern for multi-platform bots. A single codebase that deploys to Slack, Discord, Telegram, and Microsoft Teams. In the browser demo, shows the same conversational UX that would work across messaging platforms.",
    apiEndpoints: ["searchActive", "decode", "predict", "history", "incentives", "soldSummary"],
    inputParams: [],
  },
  {
    id: "chat-chainlit", name: "Market Analyst (Chainlit)", tagline: "Python MCP chat with tool execution visualization",
    segment: "Chat Demos", tool: "chat",
    description: "Demonstrates the Chainlit pattern for Python-based chat applications. Features built-in tool execution steps with expandable input/output visualization. Ideal for data science and analytics use cases where tool execution transparency is important.",
    apiEndpoints: ["searchActive", "decode", "predict", "history", "incentives", "soldSummary"],
    inputParams: [],
  },
  {
    id: "chat-streamlit", name: "Quick Market Check (Streamlit)", tagline: "Lightweight Python chat for data teams",
    segment: "Chat Demos", tool: "chat",
    description: "Demonstrates the Streamlit pattern \u2014 the lowest-barrier chat implementation. Built as a single Python file with Streamlit's native chat components. Expandable tool call sections show raw API responses. Perfect for data teams who want quick access to market data.",
    apiEndpoints: ["searchActive", "decode", "predict", "history", "incentives", "soldSummary"],
    inputParams: [],
  },
  {
    id: "chat-langchain", name: "AI Agent Explorer (LangChain)", tagline: "Autonomous agent with visible reasoning chains",
    segment: "Chat Demos", tool: "chat",
    description: "Demonstrates the LangChain/LangGraph ReAct agent pattern. The agent autonomously decides which tools to call and in what order, showing its reasoning chain in the chat. Ideal for complex multi-step queries that require the AI to plan its approach.",
    apiEndpoints: ["searchActive", "decode", "predict", "history", "incentives", "soldSummary"],
    inputParams: [],
  },
];

/** Derivative API endpoints (composite handlers served at /api/proxy/{name}) */
export const DERIVATIVE_APIS = [
  {
    name: "estimate-trade-in",
    title: "Trade-In Estimator",
    description: "Estimates trade-in, private party, and instant cash values for a vehicle. Combines VIN decoding, retail and wholesale price predictions, and recent sold comparables into a single response.",
    method: "POST",
    endpoint: "/api/proxy/estimate-trade-in",
    underlyingApis: ["VIN Decode", "Price Prediction (franchise)", "Price Prediction (independent)", "Search Recent/Sold"],
    params: {
      vin: { type: "string", required: true, desc: "17-character VIN" },
      miles: { type: "number", required: false, desc: "Current mileage" },
      zip: { type: "string", required: false, desc: "ZIP code for regional pricing" },
    },
    exampleRequest: { vin: "5YJSA1DG9DFP14705", miles: 45000, zip: "90210", _auth_mode: "api_key", _auth_value: "YOUR_API_KEY" },
    exampleResponse: { decode: { year: 2013, make: "Tesla", model: "Model S", trim: "Performance", body_type: "Sedan", engine: "Electric", transmission: "1-Speed Automatic", drivetrain: "RWD", fuel_type: "Electric", msrp: 87400, exterior_color: "Red" }, retail: { predicted_price: 28500, price_range: { low: 25200, high: 31800 }, confidence_score: 0.87, comparables_count: 18 }, wholesale: { predicted_price: 24200, price_range: { low: 21500, high: 26900 }, confidence_score: 0.82, comparables_count: 12 }, soldComps: { num_found: 42, stats: { price: { mean: 26800, min: 19500, max: 34200, std: 3150 } }, listings: [{ vin: "5YJSA1E2XEF123456", year: 2014, make: "Tesla", model: "Model S", price: 27500, miles: 52000, sold_date: "2024-11-15" }] } },
  },
  {
    name: "evaluate-deal",
    title: "Deal Evaluator",
    description: "Comprehensive deal evaluation. Decodes VIN, predicts fair market price, retrieves listing history, and finds comparable active listings to determine if a deal is good, fair, or overpriced.",
    method: "POST",
    endpoint: "/api/proxy/evaluate-deal",
    underlyingApis: ["VIN Decode", "Price Prediction", "Car History", "Search Active"],
    params: {
      vin: { type: "string", required: true, desc: "17-character VIN" },
      zip: { type: "string", required: false, desc: "Buyer's ZIP code" },
      miles: { type: "number", required: false, desc: "Current mileage" },
    },
    exampleRequest: { vin: "1HGCV1F34LA000001", zip: "60601", _auth_mode: "api_key", _auth_value: "YOUR_API_KEY" },
    exampleResponse: { decode: { year: 2020, make: "Honda", model: "Accord", trim: "Sport 1.5T", body_type: "Sedan", engine: "1.5L Turbo I4", transmission: "CVT", drivetrain: "FWD", fuel_type: "Gasoline", msrp: 28400 }, prediction: { predicted_price: 24500, price_range: { low: 22100, high: 26900 }, confidence_score: 0.91, comparables_count: 24 }, activeComps: { num_found: 156, stats: { price: { mean: 25200, min: 18900, max: 31500 }, miles: { mean: 38200 }, dom: { mean: 28 } }, listings: [{ vin: "1HGCV1F38MA112233", year: 2021, make: "Honda", model: "Accord", trim: "Sport", price: 24800, miles: 35200, dealer: { name: "Honda of Chicago", city: "Chicago", state: "IL" } }] }, history: { listings: [{ price: 27500, miles: 15000, first_seen: "2022-03-10", last_seen: "2022-05-20", dealer: "AutoNation Honda" }, { price: 25900, miles: 28000, first_seen: "2023-08-15", last_seen: "2024-01-10", dealer: "CarMax Chicago" }] } },
  },
  {
    name: "appraiser-workbench",
    title: "Appraiser Workbench",
    description: "Full vehicle appraisal with retail and wholesale valuations, active and sold comparables (25 each), listing history, and VIN-decoded specs. The most comprehensive single-call valuation endpoint.",
    method: "POST",
    endpoint: "/api/proxy/appraiser-workbench",
    underlyingApis: ["VIN Decode", "Price Prediction (franchise)", "Price Prediction (independent)", "Car History", "Search Active", "Search Recent/Sold"],
    params: {
      vin: { type: "string", required: true, desc: "17-character VIN" },
      miles: { type: "number", required: false, desc: "Mileage" },
      zip: { type: "string", required: false, desc: "ZIP code" },
    },
    exampleRequest: { vin: "WBA7E2C51JG123456", miles: 35000, zip: "90210", _auth_mode: "api_key", _auth_value: "YOUR_API_KEY" },
    exampleResponse: { decode: { year: 2018, make: "BMW", model: "7 Series", trim: "740i", body_type: "Sedan", engine: "3.0L Turbo I6", transmission: "8-Speed Automatic", drivetrain: "RWD", fuel_type: "Gasoline", msrp: 83650, city_mpg: 21, highway_mpg: 29 }, retail: { predicted_price: 38900, price_range: { low: 35400, high: 42400 }, confidence_score: 0.84, comparables_count: 14 }, wholesale: { predicted_price: 33200, price_range: { low: 30100, high: 36300 }, confidence_score: 0.79 }, activeComps: { num_found: 89, stats: { price: { mean: 40200, min: 28500, max: 55000 }, miles: { mean: 42000 }, dom: { mean: 35 } }, listings: [{ vin: "WBA7F2C58JG445566", year: 2018, make: "BMW", model: "7 Series", price: 37900, miles: 38500, dealer: { name: "BMW Beverly Hills", city: "Beverly Hills", state: "CA" } }] }, soldComps: { num_found: 45, stats: { price: { mean: 36800, min: 26000, max: 48500 } } }, history: { listings: [{ price: 52900, miles: 12000, first_seen: "2020-06-01", dealer: "BMW of Manhattan" }, { price: 41500, miles: 28000, first_seen: "2022-11-10", dealer: "Carvana" }] } },
  },
  {
    name: "claims-valuation",
    title: "Claims Valuation",
    description: "Insurance claims valuation with fair market value, sold comparables, regional pricing data, and replacement vehicle options. Everything needed for total-loss determination.",
    method: "POST",
    endpoint: "/api/proxy/claims-valuation",
    underlyingApis: ["VIN Decode", "Price Prediction", "Search Recent/Sold", "Sold Vehicle Summary", "Search Active"],
    params: {
      vin: { type: "string", required: true, desc: "Claimed vehicle VIN" },
      miles: { type: "number", required: false, desc: "Mileage at time of loss" },
      zip: { type: "string", required: true, desc: "Claim location ZIP" },
    },
    exampleRequest: { vin: "5YJSA1DG9DFP14705", miles: 50000, zip: "90210", _auth_mode: "api_key", _auth_value: "YOUR_API_KEY" },
    exampleResponse: { decode: { year: 2013, make: "Tesla", model: "Model S", trim: "Performance", body_type: "Sedan", engine: "Electric", fuel_type: "Electric", msrp: 87400 }, fmvResult: { predicted_price: 27500, price_range: { low: 24000, high: 31000 }, confidence_score: 0.85 }, soldComps: { num_found: 38, stats: { price: { mean: 26200, min: 18500, max: 33800 } }, listings: [{ year: 2013, make: "Tesla", model: "Model S", price: 25800, miles: 55000, sold_date: "2024-10-22" }] }, regionalData: { rankings: [{ state: "CA", average_sale_price: 28900, sold_count: 142 }, { state: "FL", average_sale_price: 26100, sold_count: 67 }] }, replacements: { num_found: 12, listings: [{ year: 2014, make: "Tesla", model: "Model S", price: 26500, miles: 48000, dealer: { name: "Tesla Beverly Hills", city: "Beverly Hills", state: "CA" } }] } },
  },
  {
    name: "generate-vin-market-report",
    title: "VIN Market Report",
    description: "Complete market intelligence report for a single VIN. Includes specs, pricing (retail + wholesale), market position, comparables, history, and available incentives. Designed for embedding as a widget.",
    method: "POST",
    endpoint: "/api/proxy/generate-vin-market-report",
    underlyingApis: ["VIN Decode", "Price Prediction (franchise)", "Price Prediction (independent)", "Car History", "Search Active", "Search Recent/Sold", "Sold Vehicle Summary", "OEM Incentives"],
    params: {
      vin: { type: "string", required: true, desc: "17-character VIN" },
      miles: { type: "number", required: false, desc: "Mileage" },
      zip: { type: "string", required: false, desc: "ZIP code" },
    },
    exampleRequest: { vin: "1HGCV1F34LA000001", zip: "60601", _auth_mode: "api_key", _auth_value: "YOUR_API_KEY" },
    exampleResponse: { decode: { year: 2020, make: "Honda", model: "Accord", trim: "Sport 1.5T", body_type: "Sedan", engine: "1.5L Turbo I4", drivetrain: "FWD", fuel_type: "Gasoline", msrp: 28400 }, retail: { predicted_price: 24500, price_range: { low: 22100, high: 26900 }, confidence_score: 0.91 }, wholesale: { predicted_price: 20800, price_range: { low: 18500, high: 23100 } }, history: { listings: [{ price: 27500, miles: 15000, first_seen: "2022-03-10", dealer: "AutoNation Honda" }] }, activeComps: { num_found: 156, stats: { price: { mean: 25200 }, miles: { mean: 38200 } } }, soldComps: { num_found: 89, stats: { price: { mean: 23800 } } }, soldSummary: { rankings: [{ make: "Honda", model: "Accord", sold_count: 4520, average_sale_price: 24100 }] }, incentives: [{ title: "Honda APR Special", type: "apr", value: "2.9% for 60 months", expires: "2025-03-31" }] },
  },
  {
    name: "search-cars",
    title: "Enhanced Car Search",
    description: "Active inventory search with pre-configured stats, facets, dealer objects, build objects, and photos. A convenience wrapper over the base search that returns a richer response.",
    method: "POST",
    endpoint: "/api/proxy/search-cars",
    underlyingApis: ["Search Active"],
    params: {
      makes: { type: "string", required: false, desc: "Comma-separated makes" },
      bodyTypes: { type: "string", required: false, desc: "Body types" },
      yearRange: { type: "string", required: false, desc: "Year range" },
      priceRange: { type: "string", required: false, desc: "Price range" },
      zip: { type: "string", required: false, desc: "ZIP code" },
      radius: { type: "number", required: false, desc: "Miles" },
      rows: { type: "number", required: false, desc: "Results (default 12)" },
    },
    exampleRequest: { makes: "Toyota", zip: "90210", radius: 50, rows: 10, _auth_mode: "api_key", _auth_value: "YOUR_API_KEY" },
    exampleResponse: { num_found: 4521, listings: [{ vin: "4T1BF1FK5HU123456", year: 2017, make: "Toyota", model: "Camry", trim: "SE", price: 18900, miles: 62000, body_type: "Sedan", fuel_type: "Gasoline", days_on_market: 22, dealer: { name: "Toyota Santa Monica", city: "Santa Monica", state: "CA" } }, { vin: "2T1BURHE8JC654321", year: 2018, make: "Toyota", model: "Corolla", trim: "LE", price: 16500, miles: 48000, body_type: "Sedan", dealer: { name: "AutoNation Toyota", city: "Los Angeles", state: "CA" } }], stats: { price: { mean: 32400, min: 8900, max: 72000, std: 12500 }, miles: { mean: 45200, min: 5, max: 185000 } }, facets: { make: [{ value: "Toyota", count: 4521 }], body_type: [{ value: "SUV", count: 1823 }, { value: "Sedan", count: 1205 }, { value: "Truck", count: 891 }] } },
  },
  {
    name: "compare-cars",
    title: "Car Comparison",
    description: "Side-by-side comparison of 2+ vehicles. Decodes each VIN for full specs and predicts market prices for each.",
    method: "POST",
    endpoint: "/api/proxy/compare-cars",
    underlyingApis: ["VIN Decode (per VIN)", "Price Prediction (per VIN)"],
    params: {
      vins: { type: "string[]", required: true, desc: "Array of VINs to compare" },
      zip: { type: "string", required: false, desc: "ZIP for pricing context" },
    },
    exampleRequest: { vins: ["1HGCV1F34LA000001", "5YJSA1DG9DFP14705"], zip: "90210", _auth_mode: "api_key", _auth_value: "YOUR_API_KEY" },
    exampleResponse: { comparisons: [{ vin: "1HGCV1F34LA000001", decode: { year: 2020, make: "Honda", model: "Accord", trim: "Sport 1.5T", engine: "1.5L Turbo I4", msrp: 28400 }, price: { predicted_price: 24500, price_range: { low: 22100, high: 26900 } } }, { vin: "5YJSA1DG9DFP14705", decode: { year: 2013, make: "Tesla", model: "Model S", trim: "Performance", engine: "Electric", msrp: 87400 }, price: { predicted_price: 28500, price_range: { low: 25200, high: 31800 } } }] },
  },
  {
    name: "get-market-index",
    title: "Market Index",
    description: "Used car market index data. Returns top brands by volume and price, plus body type segment analysis. Filterable by state.",
    method: "POST",
    endpoint: "/api/proxy/get-market-index",
    underlyingApis: ["Sold Vehicle Summary (by make)", "Sold Vehicle Summary (by body type)"],
    params: {
      state: { type: "string", required: false, desc: "State abbreviation" },
    },
    exampleRequest: { state: "CA", _auth_mode: "api_key", _auth_value: "YOUR_API_KEY" },
    exampleResponse: { summary: { rankings: [{ make: "Toyota", sold_count: 18420, average_sale_price: 29800 }, { make: "Honda", sold_count: 12350, average_sale_price: 26400 }, { make: "Ford", sold_count: 11200, average_sale_price: 31500 }, { make: "Chevrolet", sold_count: 9800, average_sale_price: 28900 }, { make: "BMW", sold_count: 6540, average_sale_price: 38200 }] }, segments: { rankings: [{ body_type: "SUV", sold_count: 34500, average_sale_price: 33200 }, { body_type: "Sedan", sold_count: 22100, average_sale_price: 25600 }, { body_type: "Truck", sold_count: 15800, average_sale_price: 38500 }] } },
  },
  {
    name: "scan-lot-pricing",
    title: "Lot Pricing Scan",
    description: "Full dealer lot inventory with market pricing comparison and demand hot list.",
    method: "POST",
    endpoint: "/api/proxy/scan-lot-pricing",
    underlyingApis: ["Search Active (dealer inventory)", "Sold Vehicle Summary (hot list)"],
    params: {
      dealerId: { type: "string", required: true, desc: "Dealer ID" },
      state: { type: "string", required: true, desc: "State for demand data" },
    },
    exampleRequest: { dealerId: "abc123", state: "TX", _auth_mode: "api_key", _auth_value: "YOUR_API_KEY" },
    exampleResponse: { inventory: { num_found: 87, listings: [{ vin: "5TFAX5GN2LX123456", year: 2020, make: "Toyota", model: "Tundra", price: 38900, miles: 42000, days_on_market: 18 }, { vin: "1G1YY22G965112233", year: 2019, make: "Chevrolet", model: "Corvette", price: 48500, miles: 22000, days_on_market: 45 }], stats: { price: { mean: 31200 }, miles: { mean: 38500 }, dom: { mean: 32 } } }, hotList: { rankings: [{ make: "Toyota", model: "RAV4", sold_count: 890, average_days_on_market: 18 }, { make: "Honda", model: "CR-V", sold_count: 720, average_days_on_market: 21 }, { make: "Ford", model: "F-150", sold_count: 1150, average_days_on_market: 15 }] } },
  },
  {
    name: "stocking-intelligence",
    title: "Stocking Intelligence",
    description: "Market demand data by make/model and body type for a state. Helps dealers decide what to stock.",
    method: "POST",
    endpoint: "/api/proxy/stocking-intelligence",
    underlyingApis: ["Sold Vehicle Summary (by make/model)", "Sold Vehicle Summary (by body type)"],
    params: {
      state: { type: "string", required: true, desc: "State abbreviation" },
    },
    exampleRequest: { state: "TX", _auth_mode: "api_key", _auth_value: "YOUR_API_KEY" },
    exampleResponse: { demandData: { rankings: [{ make: "Ford", model: "F-150", sold_count: 3250 }, { make: "Toyota", model: "RAV4", sold_count: 1890 }, { make: "Chevrolet", model: "Silverado 1500", sold_count: 2810 }, { make: "Honda", model: "CR-V", sold_count: 1420 }, { make: "Toyota", model: "Camry", sold_count: 1380 }] }, segmentDemand: { rankings: [{ body_type: "Truck", sold_count: 12500, average_sale_price: 38200, average_days_on_market: 19 }, { body_type: "SUV", sold_count: 15800, average_sale_price: 32400, average_days_on_market: 24 }, { body_type: "Sedan", sold_count: 8900, average_sale_price: 24100, average_days_on_market: 28 }] } },
  },
  {
    name: "comparables-explorer",
    title: "Comparables Explorer",
    description: "Flexible comparable search by VIN or make/model/year. Returns both active and sold comparables with optional price prediction.",
    method: "POST",
    endpoint: "/api/proxy/comparables-explorer",
    underlyingApis: ["VIN Decode (optional)", "Search Active", "Search Recent/Sold", "Price Prediction (optional)"],
    params: {
      vin: { type: "string", required: false, desc: "VIN (optional)" },
      make: { type: "string", required: false, desc: "Make" },
      model: { type: "string", required: false, desc: "Model" },
      year: { type: "string", required: false, desc: "Year" },
      zip: { type: "string", required: false, desc: "ZIP" },
      radius: { type: "number", required: false, desc: "Radius (default 100)" },
    },
    exampleRequest: { make: "Toyota", model: "Camry", year: "2022", zip: "90210", _auth_mode: "api_key", _auth_value: "YOUR_API_KEY" },
    exampleResponse: { decode: null, activeComps: { num_found: 234, stats: { price: { mean: 26800, min: 21500, max: 33200 }, miles: { mean: 32400 }, dom: { mean: 26 } }, listings: [{ vin: "4T1C11AK7NU123456", year: 2022, make: "Toyota", model: "Camry", trim: "SE", price: 25900, miles: 28000, dealer: { name: "Toyota of Hollywood", city: "Hollywood", state: "CA" } }] }, soldComps: { num_found: 178, stats: { price: { mean: 25200, min: 19800, max: 31500 } }, listings: [{ year: 2022, make: "Toyota", model: "Camry", price: 24800, miles: 35000, sold_date: "2024-11-01" }] }, prediction: null },
  },
  {
    name: "find-auction-arbitrage",
    title: "Auction Arbitrage Finder",
    description: "Calculates wholesale-to-retail spread for each VIN. Predicts both franchise (retail) and independent (wholesale) prices to identify profit opportunities.",
    method: "POST",
    endpoint: "/api/proxy/find-auction-arbitrage",
    underlyingApis: ["VIN Decode (per VIN)", "Price Prediction - franchise (per VIN)", "Price Prediction - independent (per VIN)"],
    params: {
      vins: { type: "string", required: true, desc: "Comma-separated VINs" },
      zip: { type: "string", required: true, desc: "Market ZIP" },
    },
    exampleRequest: { vins: "5YJSA1DG9DFP14705,1HGCV1F34LA000001", zip: "90210", _auth_mode: "api_key", _auth_value: "YOUR_API_KEY" },
    exampleResponse: { results: [{ vin: "5YJSA1DG9DFP14705", decode: { year: 2013, make: "Tesla", model: "Model S", trim: "Performance" }, retail: { predicted_price: 28500 }, wholesale: { predicted_price: 24200 }, spread: 4300, spreadPct: 15.1 }, { vin: "1HGCV1F34LA000001", decode: { year: 2020, make: "Honda", model: "Accord", trim: "Sport 1.5T" }, retail: { predicted_price: 24500 }, wholesale: { predicted_price: 20800 }, spread: 3700, spreadPct: 15.1 }] },
  },
  {
    name: "evaluate-loan-application",
    title: "Loan Application Evaluator",
    description: "Collateral assessment for auto loan underwriting. Returns retail and wholesale valuations, depreciation history, and sold comparables.",
    method: "POST",
    endpoint: "/api/proxy/evaluate-loan-application",
    underlyingApis: ["VIN Decode", "Price Prediction (franchise)", "Price Prediction (independent)", "Car History", "Search Recent/Sold"],
    params: {
      vin: { type: "string", required: true, desc: "Vehicle VIN" },
      miles: { type: "number", required: false, desc: "Mileage" },
      zip: { type: "string", required: false, desc: "Borrower ZIP" },
    },
    exampleRequest: { vin: "WBA7E2C51JG123456", miles: 30000, zip: "60601", _auth_mode: "api_key", _auth_value: "YOUR_API_KEY" },
    exampleResponse: { decode: { year: 2018, make: "BMW", model: "7 Series", trim: "740i", body_type: "Sedan", engine: "3.0L Turbo I6", msrp: 83650 }, retail: { predicted_price: 38900, price_range: { low: 35400, high: 42400 }, confidence_score: 0.84 }, wholesale: { predicted_price: 33200, price_range: { low: 30100, high: 36300 } }, history: { listings: [{ price: 52900, miles: 12000, first_seen: "2020-06-01", dealer: "BMW of Manhattan" }, { price: 41500, miles: 28000, first_seen: "2022-11-10", dealer: "Carvana" }] }, soldComps: { num_found: 45, stats: { price: { mean: 36800, min: 26000, max: 48500 } } } },
  },
  {
    name: "evaluate-incentive-deal",
    title: "Incentive-Adjusted Deal Evaluator",
    description: "Evaluates a deal with OEM incentives. Returns vehicle specs, predicted price, all available incentives, and comparable listings.",
    method: "POST",
    endpoint: "/api/proxy/evaluate-incentive-deal",
    underlyingApis: ["VIN Decode", "Price Prediction", "OEM Incentives", "Search Active"],
    params: {
      vin: { type: "string", required: true, desc: "VIN" },
      miles: { type: "number", required: false, desc: "Mileage" },
      zip: { type: "string", required: true, desc: "ZIP for incentives" },
    },
    exampleRequest: { vin: "1HGCV1F34LA000001", zip: "60601", _auth_mode: "api_key", _auth_value: "YOUR_API_KEY" },
    exampleResponse: { decode: { year: 2020, make: "Honda", model: "Accord", trim: "Sport 1.5T", msrp: 28400 }, prediction: { predicted_price: 24500, price_range: { low: 22100, high: 26900 } }, incentives: [{ title: "Honda Loyalty Bonus", type: "cash", value: "$500 cash back", eligible: true }, { title: "Honda APR Special", type: "apr", value: "2.9% for 60 months", eligible: true }], activeComps: { num_found: 78, stats: { price: { mean: 25200 } }, listings: [{ year: 2020, make: "Honda", model: "Accord", price: 23900, miles: 41000 }] } },
  },
  {
    name: "benchmark-insurance-premiums",
    title: "Insurance Premium Benchmark",
    description: "Market-level analysis by body type, fuel type, and state for insurance premium setting.",
    method: "POST",
    endpoint: "/api/proxy/benchmark-insurance-premiums",
    underlyingApis: ["Sold Vehicle Summary (body type)", "Sold Vehicle Summary (body type + fuel type)", "Sold Vehicle Summary (state)"],
    params: {},
    exampleRequest: { _auth_mode: "api_key", _auth_value: "YOUR_API_KEY" },
    exampleResponse: { byBodyType: { rankings: [{ body_type: "SUV", sold_count: 245000, average_sale_price: 33200 }, { body_type: "Sedan", sold_count: 182000, average_sale_price: 25600 }, { body_type: "Truck", sold_count: 156000, average_sale_price: 38500 }] }, byFuelType: { rankings: [{ body_type: "SUV", fuel_type_category: "Gas", sold_count: 198000, average_sale_price: 34100 }, { body_type: "SUV", fuel_type_category: "Electric", sold_count: 18500, average_sale_price: 42800 }, { body_type: "SUV", fuel_type_category: "Hybrid", sold_count: 28500, average_sale_price: 36200 }] }, byState: { rankings: [{ state: "CA", sold_count: 89000, average_sale_price: 32400 }, { state: "TX", sold_count: 78000, average_sale_price: 31200 }, { state: "FL", sold_count: 65000, average_sale_price: 29800 }] } },
  },
  {
    name: "generate-market-briefing",
    title: "Market Briefing",
    description: "Executive market summary: top brands, body type analysis, and regional price leaders.",
    method: "POST",
    endpoint: "/api/proxy/generate-market-briefing",
    underlyingApis: ["Sold Vehicle Summary (by make)", "Sold Vehicle Summary (by body type)", "Sold Vehicle Summary (by state)"],
    params: {},
    exampleRequest: { _auth_mode: "api_key", _auth_value: "YOUR_API_KEY" },
    exampleResponse: { byMake: { rankings: [{ make: "Toyota", sold_count: 142000, average_sale_price: 29800 }, { make: "Ford", sold_count: 128000, average_sale_price: 33500 }, { make: "Chevrolet", sold_count: 115000, average_sale_price: 30200 }, { make: "Honda", sold_count: 98000, average_sale_price: 26400 }, { make: "Hyundai", sold_count: 72000, average_sale_price: 24800 }] }, byBodyType: { rankings: [{ body_type: "SUV", sold_count: 245000, average_sale_price: 33200 }, { body_type: "Sedan", sold_count: 182000, average_sale_price: 25600 }, { body_type: "Truck", sold_count: 156000, average_sale_price: 38500 }] }, byState: { rankings: [{ state: "CA", average_sale_price: 32400 }, { state: "NY", average_sale_price: 30100 }, { state: "TX", average_sale_price: 31200 }, { state: "FL", average_sale_price: 29800 }] } },
  },
  {
    name: "stress-test-portfolio",
    title: "Portfolio Stress Test",
    description: "Batch VIN valuation for portfolio stress testing. Decodes and prices each vehicle.",
    method: "POST",
    endpoint: "/api/proxy/stress-test-portfolio",
    underlyingApis: ["VIN Decode (per VIN)", "Price Prediction (per VIN)"],
    params: {
      vins: { type: "string", required: true, desc: "Comma-separated VINs" },
      zip: { type: "string", required: true, desc: "Market ZIP" },
    },
    exampleRequest: { vins: "5YJSA1DG9DFP14705,WBA7E2C51JG123456", zip: "90210", _auth_mode: "api_key", _auth_value: "YOUR_API_KEY" },
    exampleResponse: { results: [{ vin: "5YJSA1DG9DFP14705", decode: { year: 2013, make: "Tesla", model: "Model S", trim: "Performance", msrp: 87400 }, prediction: { predicted_price: 28500, price_range: { low: 25200, high: 31800 } } }, { vin: "WBA7E2C51JG123456", decode: { year: 2018, make: "BMW", model: "7 Series", trim: "740i", msrp: 83650 }, prediction: { predicted_price: 38900, price_range: { low: 35400, high: 42400 } } }] },
  },
  {
    name: "analyze-dealer-conquest",
    title: "Dealer Conquest Analysis",
    description: "Compares dealer inventory against broader market. Identifies inventory gaps and conquest opportunities based on local demand.",
    method: "POST",
    endpoint: "/api/proxy/analyze-dealer-conquest",
    underlyingApis: ["Search Active (dealer)", "Search Active (market)", "Sold Vehicle Summary"],
    params: {
      dealer_id: { type: "string", required: true, desc: "Your dealer ID" },
      zip: { type: "string", required: true, desc: "Market ZIP" },
      radius: { type: "number", required: false, desc: "Market radius" },
      state: { type: "string", required: true, desc: "State" },
    },
    exampleRequest: { dealer_id: "abc123", zip: "75201", state: "TX", _auth_mode: "api_key", _auth_value: "YOUR_API_KEY" },
    exampleResponse: { myInventory: { num_found: 87, facets: { make: [{ value: "Toyota", count: 22 }, { value: "Honda", count: 18 }], body_type: [{ value: "SUV", count: 35 }, { value: "Sedan", count: 28 }] } }, marketInventory: { num_found: 4520, facets: { make: [{ value: "Toyota", count: 680 }, { value: "Ford", count: 590 }, { value: "Chevrolet", count: 520 }], body_type: [{ value: "SUV", count: 1800 }, { value: "Truck", count: 1200 }] } }, demand: { rankings: [{ make: "Ford", model: "F-150", sold_count: 3250 }, { make: "Toyota", model: "RAV4", sold_count: 1890 }] } },
  },
  {
    name: "find-incentive-deals",
    title: "Multi-OEM Incentive Scanner",
    description: "Scans incentives from multiple manufacturers for a ZIP code. Returns all available deals across brands.",
    method: "POST",
    endpoint: "/api/proxy/find-incentive-deals",
    underlyingApis: ["OEM Incentives (per make)"],
    params: {
      makes: { type: "string", required: false, desc: "Comma-separated makes (defaults to top 10)" },
      zip: { type: "string", required: true, desc: "ZIP code" },
    },
    exampleRequest: { zip: "90210", _auth_mode: "api_key", _auth_value: "YOUR_API_KEY" },
    exampleResponse: { results: [{ make: "Toyota", data: { incentives: [{ title: "Toyota Cash Back", value: "$2,000 on RAV4", type: "cash", expires: "2025-03-31" }] } }, { make: "Honda", data: { incentives: [{ title: "Honda APR Special", value: "1.9% for 36 months", type: "apr", expires: "2025-04-30" }] } }, { make: "Ford", data: { incentives: [{ title: "Ford Bonus Cash", value: "$3,500 on F-150", type: "cash" }] } }, { make: "Hyundai", data: { incentives: [{ title: "Hyundai Trade-In Bonus", value: "$1,500 trade-in bonus", type: "cash" }] } }] },
  },
  {
    name: "trace-vin-history",
    title: "VIN History Trace",
    description: "Full listing timeline with VIN decode and current price prediction.",
    method: "POST",
    endpoint: "/api/proxy/trace-vin-history",
    underlyingApis: ["VIN Decode", "Car History", "Price Prediction"],
    params: {
      vin: { type: "string", required: true, desc: "17-character VIN" },
      miles: { type: "number", required: false, desc: "Mileage" },
      zip: { type: "string", required: false, desc: "ZIP" },
    },
    exampleRequest: { vin: "5YJSA1DG9DFP14705", zip: "90210", _auth_mode: "api_key", _auth_value: "YOUR_API_KEY" },
    exampleResponse: { decode: { year: 2013, make: "Tesla", model: "Model S", trim: "Performance", body_type: "Sedan", engine: "Electric", msrp: 87400 }, history: { listings: [{ price: 78500, miles: 1200, first_seen: "2013-12-01", last_seen: "2014-03-15", dealer: "Tesla Palo Alto", status: "sold" }, { price: 54200, miles: 18000, first_seen: "2015-08-20", dealer: "CarMax Burbank", status: "sold" }, { price: 38900, miles: 32000, first_seen: "2018-05-10", dealer: "Shift.com" }, { price: 29500, miles: 45000, first_seen: "2021-01-15", dealer: "Vroom" }] }, prediction: { predicted_price: 28500, price_range: { low: 25200, high: 31800 }, confidence_score: 0.87 } },
  },
  {
    name: "generate-pricing-report",
    title: "Pricing Report",
    description: "Shareable pricing report: VIN specs, predicted price, active and sold comparables.",
    method: "POST",
    endpoint: "/api/proxy/generate-pricing-report",
    underlyingApis: ["VIN Decode", "Price Prediction", "Search Active", "Search Recent/Sold"],
    params: {
      vin: { type: "string", required: true, desc: "VIN" },
      miles: { type: "number", required: false, desc: "Mileage" },
      zip: { type: "string", required: false, desc: "ZIP" },
    },
    exampleRequest: { vin: "1HGCV1F34LA000001", zip: "60601", _auth_mode: "api_key", _auth_value: "YOUR_API_KEY" },
    exampleResponse: { decode: { year: 2020, make: "Honda", model: "Accord", trim: "Sport 1.5T", body_type: "Sedan", msrp: 28400 }, prediction: { predicted_price: 24500, price_range: { low: 22100, high: 26900 }, confidence_score: 0.91 }, activeComps: { num_found: 156, stats: { price: { mean: 25200, min: 18900, max: 31500 } }, listings: [{ vin: "1HGCV1F38MA112233", year: 2021, make: "Honda", model: "Accord", price: 24800, miles: 35200 }] }, soldComps: { num_found: 89, stats: { price: { mean: 23800, min: 17500, max: 29200 } }, listings: [{ year: 2020, make: "Honda", model: "Accord", price: 23200, miles: 42000, sold_date: "2024-10-15" }] } },
  },
  {
    name: "oem-incentives-explorer",
    title: "OEM Incentives Explorer",
    description: "Fetches incentives for a make and optionally compares with other brands.",
    method: "POST",
    endpoint: "/api/proxy/oem-incentives-explorer",
    underlyingApis: ["OEM Incentives", "OEM Incentives (per compare make)"],
    params: {
      make: { type: "string", required: true, desc: "Primary make" },
      model: { type: "string", required: false, desc: "Model" },
      zip: { type: "string", required: true, desc: "ZIP" },
      compareMakes: { type: "string[]", required: false, desc: "Brands to compare" },
    },
    exampleRequest: { make: "Toyota", zip: "90210", compareMakes: ["Honda", "Hyundai"], _auth_mode: "api_key", _auth_value: "YOUR_API_KEY" },
    exampleResponse: { make: "Toyota", incentives: [{ title: "Toyota Cash Back", value: "$2,000 on RAV4", type: "cash", expires: "2025-03-31" }, { title: "Toyota APR Special", value: "2.9% for 60 months on Camry", type: "apr" }], compareIncentives: [{ make: "Honda", data: { incentives: [{ title: "Honda Loyalty Bonus", value: "$750", type: "cash" }] } }, { make: "Hyundai", data: { incentives: [{ title: "Hyundai Bonus Cash", value: "$2,500 on Tucson", type: "cash" }] } }] },
  },
  {
    name: "route-wholesale-vehicles",
    title: "Wholesale Vehicle Router",
    description: "Batch VIN decode and pricing for wholesale routing decisions.",
    method: "POST",
    endpoint: "/api/proxy/route-wholesale-vehicles",
    underlyingApis: ["VIN Decode (per VIN)", "Price Prediction (per VIN)"],
    params: {
      vins: { type: "string", required: true, desc: "Comma-separated VINs" },
      zip: { type: "string", required: true, desc: "Market ZIP" },
    },
    exampleRequest: { vins: "5YJSA1DG9DFP14705,1HGCV1F34LA000001", zip: "90210", _auth_mode: "api_key", _auth_value: "YOUR_API_KEY" },
    exampleResponse: { results: [{ vin: "5YJSA1DG9DFP14705", decode: { year: 2013, make: "Tesla", model: "Model S", trim: "Performance" }, prediction: { predicted_price: 28500 } }, { vin: "1HGCV1F34LA000001", decode: { year: 2020, make: "Honda", model: "Accord", trim: "Sport 1.5T" }, prediction: { predicted_price: 24500 } }] },
  },
  {
    name: "score-dealer-fit",
    title: "Dealer Fit Scorer",
    description: "Score vehicles against a dealer's profile. Batch VIN decode and pricing.",
    method: "POST",
    endpoint: "/api/proxy/score-dealer-fit",
    underlyingApis: ["VIN Decode (per VIN)", "Price Prediction (per VIN)"],
    params: {
      dealer_id: { type: "string", required: true, desc: "Dealer ID" },
      vins: { type: "string", required: true, desc: "Comma-separated VINs" },
      zip: { type: "string", required: true, desc: "Dealer ZIP" },
    },
    exampleRequest: { dealer_id: "abc123", vins: "5YJSA1DG9DFP14705", zip: "90210", _auth_mode: "api_key", _auth_value: "YOUR_API_KEY" },
    exampleResponse: { dealerId: "abc123", results: [{ vin: "5YJSA1DG9DFP14705", decode: { year: 2013, make: "Tesla", model: "Model S", trim: "Performance", body_type: "Sedan" }, prediction: { predicted_price: 28500, price_range: { low: 25200, high: 31800 } } }] },
  },
  {
    name: "detect-market-anomalies",
    title: "Market Anomaly Detector",
    description: "Find pricing outliers in active inventory for a make/model.",
    method: "POST",
    endpoint: "/api/proxy/detect-market-anomalies",
    underlyingApis: ["Search Active"],
    params: {
      make: { type: "string", required: true, desc: "Make" },
      model: { type: "string", required: true, desc: "Model" },
      year: { type: "string", required: false, desc: "Year" },
      state: { type: "string", required: false, desc: "State" },
    },
    exampleRequest: { make: "Tesla", model: "Model 3", state: "CA", _auth_mode: "api_key", _auth_value: "YOUR_API_KEY" },
    exampleResponse: { results: { num_found: 450, listings: [{ vin: "5YJ3E1EA2LF123456", year: 2020, make: "Tesla", model: "Model 3", trim: "Standard Range Plus", price: 22900, miles: 48000, days_on_market: 5, dealer: { name: "Tesla Fremont", state: "CA" }, anomaly: "underpriced" }, { vin: "5YJ3E1EB8NF654321", year: 2022, make: "Tesla", model: "Model 3", trim: "Long Range", price: 55800, miles: 12000, days_on_market: 90, dealer: { name: "Private Seller", state: "CA" }, anomaly: "overpriced" }], stats: { price: { mean: 31200, min: 18500, max: 55800, std: 6800 } } } },
  },
  {
    name: "manage-fleet-lifecycle",
    title: "Fleet Lifecycle Manager",
    description: "Batch fleet valuation with replacement vehicle recommendations.",
    method: "POST",
    endpoint: "/api/proxy/manage-fleet-lifecycle",
    underlyingApis: ["VIN Decode (per VIN)", "Price Prediction (per VIN)", "Search Active (replacements)"],
    params: {
      vins: { type: "string", required: true, desc: "Fleet VINs" },
      zip: { type: "string", required: true, desc: "Fleet ZIP" },
    },
    exampleRequest: { vins: "5YJSA1DG9DFP14705,WBA7E2C51JG123456", zip: "90210", _auth_mode: "api_key", _auth_value: "YOUR_API_KEY" },
    exampleResponse: { results: [{ vin: "5YJSA1DG9DFP14705", decode: { year: 2013, make: "Tesla", model: "Model S", body_type: "Sedan" }, prediction: { predicted_price: 28500 }, depreciationRate: "8.2% annual" }, { vin: "WBA7E2C51JG123456", decode: { year: 2018, make: "BMW", model: "7 Series", body_type: "Sedan" }, prediction: { predicted_price: 38900 }, depreciationRate: "12.5% annual" }], replacements: { num_found: 25, listings: [{ year: 2024, make: "Toyota", model: "Camry", price: 28500, miles: 5000 }] } },
  },
  {
    name: "value-rental-fleet",
    title: "Rental Fleet Valuator",
    description: "Batch valuation for rental fleet vehicles. Decodes and prices each VIN.",
    method: "POST",
    endpoint: "/api/proxy/value-rental-fleet",
    underlyingApis: ["VIN Decode (per VIN)", "Price Prediction (per VIN)"],
    params: {
      vins: { type: "string", required: true, desc: "Fleet VINs" },
      zip: { type: "string", required: true, desc: "Fleet ZIP" },
    },
    exampleRequest: { vins: "5YJSA1DG9DFP14705", zip: "90210", _auth_mode: "api_key", _auth_value: "YOUR_API_KEY" },
    exampleResponse: { results: [{ vin: "5YJSA1DG9DFP14705", decode: { year: 2013, make: "Tesla", model: "Model S", trim: "Performance", body_type: "Sedan", fuel_type: "Electric" }, prediction: { predicted_price: 28500, price_range: { low: 25200, high: 31800 }, confidence_score: 0.87 }, mileageAdjustedValue: 26800, optimalRotationMiles: 60000 }] },
  },
  {
    name: "search-uk-cars",
    title: "UK Car Search",
    description: "Search UK active and recent car listings.",
    method: "POST",
    endpoint: "/api/proxy/search-uk-cars",
    underlyingApis: ["UK Active Listings", "UK Recent Listings"],
    params: {
      make: { type: "string", required: false, desc: "Make" },
      model: { type: "string", required: false, desc: "Model" },
      postal_code: { type: "string", required: false, desc: "UK postal code" },
      radius: { type: "number", required: false, desc: "Radius" },
      rows: { type: "number", required: false, desc: "Results (default 25)" },
    },
    exampleRequest: { make: "BMW", postal_code: "SW1A 1AA", rows: 10, _auth_mode: "api_key", _auth_value: "YOUR_API_KEY" },
    exampleResponse: { active: { num_found: 1250, listings: [{ year: 2020, make: "BMW", model: "3 Series", trim: "320d M Sport", price: 24995, miles: 32000, fuel_type: "Diesel", dealer: { name: "BMW Park Lane", city: "London" } }], stats: { price: { mean: 28500 } } }, recent: { num_found: 890, stats: { price: { mean: 26200 } } } },
  },
  {
    name: "get-uk-market-trends",
    title: "UK Market Trends",
    description: "UK market statistics for active and recent inventory.",
    method: "POST",
    endpoint: "/api/proxy/get-uk-market-trends",
    underlyingApis: ["UK Active Listings (stats only)", "UK Recent Listings (stats only)"],
    params: {
      make: { type: "string", required: false, desc: "Filter by make" },
    },
    exampleRequest: { make: "Volkswagen", _auth_mode: "api_key", _auth_value: "YOUR_API_KEY" },
    exampleResponse: { active: { num_found: 18500, stats: { price: { mean: 19800, min: 4500, max: 52000 }, miles: { mean: 38000 } } }, recent: { num_found: 12400, stats: { price: { mean: 17900, min: 3200, max: 48000 } } } },
  },
  {
    name: "scan-uk-lot-pricing",
    title: "UK Lot Pricing",
    description: "UK dealer inventory with recent market comparison.",
    method: "POST",
    endpoint: "/api/proxy/scan-uk-lot-pricing",
    underlyingApis: ["UK Active Listings (dealer)", "UK Recent Listings"],
    params: {
      dealer_id: { type: "string", required: true, desc: "UK dealer ID" },
      make: { type: "string", required: false, desc: "Make filter" },
    },
    exampleRequest: { dealer_id: "uk_dealer_123", _auth_mode: "api_key", _auth_value: "YOUR_API_KEY" },
    exampleResponse: { inventory: { num_found: 45, listings: [{ year: 2021, make: "Volkswagen", model: "Golf", trim: "R-Line", price: 22495, miles: 18000, fuel_type: "Petrol" }], stats: { price: { mean: 24800 }, miles: { mean: 22000 } } }, recent: { num_found: 28, stats: { price: { mean: 21500 } } } },
  },
];
